-- ============================================================================
-- سكريبت إصلاح الصلاحيات ومخطط قاعدة البيانات في Supabase
-- مركز بلال بن الحارث المزني لتحفيظ القرآن الكريم والسنة النبوية
--
-- طريقة التشغيل:
-- 1. ادخل إلى لوحة تحكم Supabase: https://supabase.com/dashboard
-- 2. اختر مشروع المركز (ynaweuhmpgjfcdtkgnfd)
-- 3. اذهب إلى قائمة SQL Editor (الأيقونة التي تشبه محرر الأكواد)
-- 4. اضغط على New Query، ثم الصق محتويات هذا الملف بالكامل
-- 5. اضغط على Run (أو Ctrl + Enter)
-- ============================================================================

-- 1) إضافة الأعمدة الإضافية لجدول الملفات الشخصية (profiles) لتخزين اسم المستخدم وكلمة المرور
alter table public.profiles add column if not exists username text;
alter table public.profiles add column if not exists password text;
alter table public.profiles add column if not exists linked_id uuid;

-- 2) فك قيد الربط الإجباري بـ auth.users لجدول profiles
-- (يتيح تسجيل الطلاب والمحفظين بدون الحاجة لإنشاء إيميلات سحابية لكل طفل أو محفظ)
alter table public.profiles drop constraint if exists profiles_id_fkey;

-- 3) جعل profile_id في جدول teachers يقبل null وفك القيد الإجباري
alter table public.teachers alter column profile_id drop not null;
alter table public.teachers drop constraint if exists teachers_profile_id_fkey;

-- 4) ضبط ترقيم الطلاب ليكون تلقائياً عند عدم التمرير ويقبل التمرير المخصص
do $$
begin
  if exists (
    select 1 from information_schema.columns 
    where table_schema = 'public' and table_name = 'students' and column_name = 'student_number'
  ) then
    alter table public.students alter column student_number set generated by default;
  end if;
exception
  when others then
    null;
end $$;

-- 5) إدراج حساب المدير الافتراضي ("أنس خميس العدولي") في جدول profiles
insert into public.profiles (id, role, full_name, username, password, email)
values (
  '00000000-0000-0000-0000-000000000001',
  'admin',
  'أنس خميس العدولي',
  'أنس خميس العدولي',
  '6129',
  'admin@bilal.center'
)
on conflict (id) do update set
  role = excluded.role,
  full_name = excluded.full_name,
  username = excluded.username,
  password = excluded.password;

-- 6) تحديث سياسات الأمان (Row Level Security - RLS)
-- السماح لتطبيق المركز بعمليات القراءة والكتابة بالـ Anon / Publishable Key
-- لحل مشكلة "new row violates row-level security policy" تماماً
do $$
declare
  t text;
  tables text[] := array[
    'profiles', 'teachers', 'parents', 'halaqat', 'students',
    'recitations', 'mistakes', 'attendance', 'exams', 'exam_results',
    'assignments', 'notes', 'recommendations', 'notifications',
    'device_tokens', 'audit_logs'
  ];
begin
  foreach t in array tables loop
    -- التأكد من تفعيل RLS
    execute format('alter table public.%I enable row level security;', t);
    
    -- حذف السياسة القديمة في حال إعادة التشغيل
    execute format('drop policy if exists "center_app_all_%s" on public.%I;', t, t);
    
    -- إنشاء السياسة الشاملة لتطبيق المركز
    execute format(
      'create policy "center_app_all_%s" on public.%I for all to anon, authenticated using (true) with check (true);',
      t, t
    );
  end loop;
end $$;
